## <u>While doing this assignment only use those concepts which have been taught till now</u>

## <u>Problem 1</u>

### As an analyst, you had to present the quarterly performance results of your client. The data which you were provided was on daily basis. To complete this task, you needed to extract the quarter from a given date. For example:

* if the date lies between 1st Jan, 2020 - 31st March, 2020, you need to extract the corresponding quarter as '2020-Q1'

* if the date lies between 1st April, 2020 - 30th June, 2020, the extracted quarter will be '2020-Q2'

* if the date lies between 1st July, 2020 - 30th September, 2020, the extracted quarter will be '2020-Q3' 

* if the date lies between 1st October, 2020 - 31st Decemeber, 2020 then the extracted quarter will be '2020-Q4'

In [30]:
# Take a proper date input from the user in the format YYYY-MM-DD. Consider this date as a string
user_date = input()

2020-11-21

In [31]:
# Write your code using if else statements to extract the quarter
date_year = user_date[:4]
date_month = user_date[5:7]

if date_month ==( '01' or '02' or '03') :
  quarter= date_year+'-Q1'

elif date_month == ('04' or '05' or '06') :
  quarter=date_year+'-Q2'

elif date_month == ('07' or '08' or '09') :
  quarter=date_year+'-Q3'

else:
  quarter=date_year+'-Q4'

# Store the quarter value in a string variable named quarter
print('Year:',date_year)
print('Month:',date_month)
print('Quarter:',quarter)

Year: 2020
Month: 11
Quarter: 2020-Q4

In [32]:
# Print the extracted quarter
print(quarter)

2020-Q4

## <u>Problem 2 </u>

* You went out in your local neighbourhood to collect the data of people residing in the locale. You surveyed 5 people and collected some data and stored that in a dictionary. You recorded their names, their age, their sex, their heights(in cms) and their weights(in kgs)

In [1]:
# Surveyed data 

locality_data = {'Name' : ['Abhinav','Sohail','Dheeraj','Rashmi','Vaishali'],
                  'Age' : [42,29,35,28,32],
                  'Sex' : ['Male', 'Male','Male','Female','Female'] , 
                  'Height' : [172,175,170,168,170],
                  'Weight' : [70,82,60,55,64]
                 }

* Find the mean and median heights and weights of the people in your locality

66.2

In [18]:
# Calculate the mean height and print it

mean_ht=sum(locality_data['Height'])/len(locality_data['Height'])
print('Mean height is',mean_ht)


# Calculate the median height and print it
n=len(locality_data['Height'])
sorted_hts=sorted(locality_data['Height'])

if n%2==0:
  median=(sorted_hts[n//2] + sorted_hts[n//2-1])/2
else:
  median=sorted_hts[n//2]
print('median height is:',median)


# Calculate the mean weight and print it
mean_wt=sum(locality_data['Weight'])/len(locality_data['Weight'])
print('Mean Weight :',mean_wt)



# Calculate the median weight and print it
n=len(locality_data['Weight'])
sorted_wts=sorted(locality_data['Weight'])

if n%2==0:
  median_wt=(sorted_wts[n//2] + sorted_wts[n//2-1])/2
else:
  median_wt=sorted_wts[n//2]
print('median weight is:',median_wt)

Mean height is 171.0
median height is: 170
Mean Weight : 66.2
median weight is: 64

* Write a Python code to print the first three elements from the list of age values corresponding to the key 'Age'

In [19]:
# Python code to print the first three elements for the key 'Age'

ages = locality_data['Age'][:3]
print(ages)

[42, 29, 35]

* Write a Python code to print the last two elements of the name list if the list of values corresponding to the key 'Name' contains the element 'Rashmi' else print 'Name not found'

In [33]:
# Your code below
if 'Rashmi' in locality_data['Name'][-2:]:
  print(locality_data['Name'][-2])
  print(locality_data['Name'][-1])
else:
  print('name not found')

Rashmi
Vaishali

## <u> Problem 3 </u>

A student will not be allowed to sit in exam if his/her attendence is less than 75%.

Take following input from user
* Number of classes held
* Number of classes attended.

In [34]:
# Enter your input

print("Number of classes held")
classes_held = int(input())

print("Number of classes attended")
classes_attended = int(input())

Number of classes held
100
Number of classes attended
67

In [35]:
# Calculate the attendance percentage
attendance = classes_attended*100/classes_held

print(f'The attendance is {attendance}')

The attendance is 67.0

And print the following statements based on the condition above

* percentage of class attended
* Is student is allowed to sit in exam or not.

In [37]:
# Your code here 
print('Attendance of the student:',attendance)
if attendance >=75:
  print('Student id allowed to attend the exam')
else:
  print('Student is not allowed to attend the exam')

Attendance of the student: 67.0
Student is not allowed to attend the exam

## <u>Problem 4</u>

### A school has following rules for grading system:
* Below 25 - F
* 25 to 45 - E
* 45 to 50 - D
* 50 to 60 - C
* 60 to 80 - B
* Above 80 - A

Keep the left number inclusive and the right number exclusive, something like (25,45) for grade E where the set is closed at 25 and open at 45.

Write a Python code which takes marks as inputs from the user and print the corresponding grade.

In [42]:
# Your input here 
print("Enter your marks")
marks = int(input())

Enter your marks
60

In [43]:
# Your code here to print the corresponding grade
if 0<marks<25:
  print('Grade F')
elif 25<=marks<45:
  print('Grade E')
elif 45<=marks<50:
  print('Grade D')
elif 50<=marks<60:
  print('Grade C')
elif 60<=marks<80:
  print('Grade B')
else:
  print('Grade A')

Grade B